### ISSUE TITLE
TargetResponseTime cannot show millisecond data

### ISSUE THREAD

**Issue by nobuhikosekiya2** [Appdynamics/aws-application-elb-monitoring-extension#3]
Hi ,

AppDynamics cannot show latency data by milliseconds. 
Showing latency in seconds without decimal value does not have  much value I think.

> aws cloudwatch get-metric-statistics --namespace AWS/ApplicationELB --metric-name TargetResponseTime --statistics Average  --period 3600 --dimensions Name=LoadBalancer,Value=app/appdLB/3b857d58ef16ef08 --region ap-northeast-1 --start-time 2019-07-21T10:40:00+0900 --end-time 2019-07-21T10:50:00+0900

{
    "Datapoints": [
        {
            "Timestamp": "2019-07-21T01:40:00Z",
            "Average": 0.011794,
            "Unit": "Seconds"
        }
    ],
    "Label": "TargetResponseTime"
}

![image](https://user-images.githubusercontent.com/35252856/61586082-60e43480-aba6-11e9-95fc-9b424f79c728.png)

BTW, this is same for Classic LoadBalancer extension

**Comment by kunalgupApDx** [comment]
The decimal value issue is not with the extension itself but with the AppDynamics platform. The current AppDynamics platform does not support decimal values. In the new platform in works, will support floats.
